// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVh92J0-T7qIxYq8soLUpoG0iLAvCyGJ0',
    appId: '1:72379381319:web:19168f8aa83a1d6e09e362',
    messagingSenderId: '72379381319',
    projectId: 'moviroo-system',
    authDomain: 'moviroo-system.firebaseapp.com',
    storageBucket: 'moviroo-system.firebasestorage.app',
    measurementId: 'G-B144Q0J5KN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMzIegm_mDgxyGfRD0mwtSV4_4zkfxAQE',
    appId: '1:72379381319:android:1e0d000500de7c4c09e362',
    messagingSenderId: '72379381319',
    projectId: 'moviroo-system',
    storageBucket: 'moviroo-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPwNKahAZlITrnrp8DC0Q7Fo-ebZsUyQM',
    appId: '1:72379381319:ios:a0a9c9efb6b590c909e362',
    messagingSenderId: '72379381319',
    projectId: 'moviroo-system',
    storageBucket: 'moviroo-system.firebasestorage.app',
    iosBundleId: 'com.example.moviroo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPwNKahAZlITrnrp8DC0Q7Fo-ebZsUyQM',
    appId: '1:72379381319:ios:a0a9c9efb6b590c909e362',
    messagingSenderId: '72379381319',
    projectId: 'moviroo-system',
    storageBucket: 'moviroo-system.firebasestorage.app',
    iosBundleId: 'com.example.moviroo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVh92J0-T7qIxYq8soLUpoG0iLAvCyGJ0',
    appId: '1:72379381319:web:08d7c22a498a3c2609e362',
    messagingSenderId: '72379381319',
    projectId: 'moviroo-system',
    authDomain: 'moviroo-system.firebaseapp.com',
    storageBucket: 'moviroo-system.firebasestorage.app',
    measurementId: 'G-ZLQJPXPFV8',
  );
}
